<head>
  <style>
    .container {
      position: relative;
      margin: 0 auto;
      width: 80%;
      margin-top: 100px;

    }

    h2 {
      font-family: Pacifico;
      font-size: 36px;
      margin: 20px auto;
      text-align: center;
    }

    img {
      border-radius: 8px;
      background: #fff;
      color: #3498db;
      font-size: 36px;
      line-height: 100px;
      margin: 10px;
      /* // padding:2%;
  //width: 100px;
  //height: 100px; */
      position: relative;
      text-align: center;

      .top {
        font-size: 70%;
        height: 70%;

        margin: 0 auto;

      }

      .bottom {
        font-size: 70%;
        width: 70%;
        margin: 0 auto;

      }
    }

    .clip {

      /* // height: 200px; */
      overflow: hidden;
      bottom: 0;
    }

    /* .center .slick-slide {
 
   height: 500px;
} */

    .center .slick-center img {
      /* //-moz-transform:scale(1.08);
  //-ms-transform:scale(1.08);
  //-o-transform:scale(1.08);
  //-webkit-transform:scale(1.08);
  transform:scale(1.0);
  //width: 150px;
  //height: 120px; */
      color: #e67e22;
      opacity: 1;

      .top {
        font-size: 90%;
        width: 90%;
        background-color: rgba(blue, 0.3);
      }

      .bottom {
        font-size: 90%;
        width: 90%;
        background-color: rgba(green, 0.3);
      }
    }

    .center img {
      opacity: 0.8;
      transition: all 300ms ease;
      bottom: 0;
      transform: scale(0.9);
    }
  </style>
</head>
<div class="container">
  <div class="slider center">
    <div class="clip">
      <img src="https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG5hdHVyZXxlbnwwfHwwfHx8MA%3D%3D" />
    </div>
    <div class="clip">
      <img src="https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG5hdHVyZXxlbnwwfHwwfHx8MA%3D%3D" />
    </div>
    <div class="clip">
      <img src="https://plus.unsplash.com/premium_photo-1673603988651-99f79e4ae7d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG5hdHVyZXxlbnwwfHwwfHx8MA%3D%3D" />
    </div>
    <div class="clip">
      <img src="https://images.unsplash.com/photo-1465189684280-6a8fa9b19a7a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fG5hdHVyZXxlbnwwfHwwfHx8MA%3D%3D" />
    </div>
    <div class="clip">
      <img src="https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fG5hdHVyZXxlbnwwfHwwfHx8MA%3D%3D" />
    </div>
  </div>
</div>